#!/bin/bash

source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_show.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_command.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_adb_shell.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_make_android.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_make_lichee.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_make_ota.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_tools.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_alias.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphdhelp.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_test_shell.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/test_string.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/clone_project.sh
source $CHIPHD_ANDROID_SCRIPT_PATH/chiphd_preinstall_apk.sh
