#!/usr/bin/env groovy
@Library('share-library@master') _

def labels = ['ws186', 'm1', 'm3', 'm4', 'm6', 'm10', 'm11', 'm12', 'm13', 'm20', 'm21', 'm22', 'gerrit1', 's0', 's1', 's2', 's3.y', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's25', 's26'] // labels for Jede types we will build on
def builders = [:]

for (x in labels) {
    def label = x // Need to bind the label variable before the closure - can't do 'for (label in labels)'

    // Create a map to pass in to the 'parallel' step so we can fire all the builds at once
    builders[label] = {

        node(label) {
            // build steps that should happen on all nodes go here
            stage(label) {
                utils.command("~/workspace/script/zzzzz-script/extend/ssh_update_script.sh")
            }
        }
    }
}

parallel builders