#!/usr/bin/env groovy
@Library('share-library@master') _

pipeline {
    agent {
        node {
            label "ws186"
            customWorkspace "/home/yafeng/jobs/${JOB_NAME}"
        }
    }

    stages {
        stage('init') {
            steps {
                echo 'init ...'
            }
        }

        stage('build') {
            steps {
                script {
                    utils.command("`dirname ${0}`/bts2zip.sh build")
                }
            }
        }

        stage('backup') {
            steps {
                script {
                    utils.command("`dirname ${0}`/bts2zip.sh backup")
                }
            }
        }
    }

    // 编译结束后问题的处理
    post {
        always {
            script {
                log.d 'This will <always> run'
            }
        }

        success {
            script {
                log.d 'This will run only if <successful>'
            }
            // mail bcc: '', body: '测试邮件', cc: '', from: '', replyTo: '', subject: '测试标题', to: 'yafeng.xing@tcl.cpm'
            // utils.send_email("构建成功...1",  email)
            // utils_.send_email("构建成功...2", email)
        }

        failure {
            script {
                log.d 'This will run only if <failed>'
            }
        }

        unstable {
            script {
                log.w 'This will run only if the run was marked as <unstable>'
            }
        }

        changed {
            script {
                log.i 'This will run only if the state of the Pipeline has <changed>'
                log.i 'For example, if the Pipeline was previously failing but is now successful'
            }
        }
    }
}
